version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:00"
      timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 10